services:
  - type: web
    name: llama-django-search
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn llama_django_search_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: llama_django_search_project.settings
